# fly.toml app configuration file generated for prompt-lab on 2025-07-06T23:07:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'prompt-lab'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = 'prompt_lab_data'
  destination = '/app/db'
  processes = ['app']

[env]
  DATABASE_URL = 'sqlite:///app/db/app.sqlite'
  DISABLE_SENTIMENT_ANALYSIS = 'true'
  ENABLE_ML_MODELS = 'false'
  TRUST_PROXY = 'true'
  EVALUATION_CONCURRENCY = '2'
  EVALUATION_MAX_CASES = '100'
  DB_MAX_CONNECTIONS = '5'
